"use client";

import { Bike, Car, CircleDot, Clock, FlaskConical, MapPin } from "lucide-react";

import { Panel } from "@/components/ui/primitives";
import type { SimulatedBooking } from "@/lib/types";
import { cn } from "@/lib/utils";

function ClassIcon({ rideClass, className }: { rideClass: string; className?: string }) {
  if (rideClass === "bike") return <Bike className={className} />;
  if (rideClass === "car") return <Car className={className} />;
  return <CircleDot className={className} />;
}

/**
 * A booking confirmation for a booking that did not happen.
 *
 * The badge is the point of this component, not decoration on it. The price,
 * the ETA and the availability behind this card come from `ride_service.py`,
 * where distance is `rng.uniform(1.5, 24.0)` and availability is a coin flip.
 * A confirmation card carrying a reference number and a price reads as a
 * completed commercial transaction, and in front of industry judges an
 * unlabelled one is a credibility problem rather than a cosmetic one.
 *
 * `booking.disclaimer` is rendered from the server's own text rather than a
 * string hardcoded here, so the claim and the data that needs the claim can
 * never drift apart.
 */
export function BookingCard({
  booking,
  replanFrom,
  className,
}: {
  booking: SimulatedBooking;
  /** HH:MM the onward journey departs from, when a replan followed. */
  replanFrom?: string | null;
  className?: string;
}) {
  return (
    <Panel className={cn("overflow-hidden border-glow-400/40", className)}>
      <div className="flex items-center gap-2 border-b border-glow-400/25 bg-glow-400/10 px-3 py-2">
        <FlaskConical className="size-3.5 shrink-0 text-glow-400" />
        <p className="text-[11px] leading-snug font-semibold text-glow-400">
          {booking.disclaimer || "Simulated booking · production requires PickMe/Uber partner API."}
        </p>
      </div>

      <div className="p-3">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="grid size-8 shrink-0 place-items-center rounded-lg bg-console-800 text-ink-300">
              <ClassIcon rideClass={booking.ride_class} className="size-4" />
            </span>
            <div className="min-w-0">
              <p className="eyebrow">Ride booked (simulated)</p>
              <p className="truncate text-sm font-semibold text-ink-100">
                {booking.ride_class_label}
              </p>
            </div>
          </div>
          <span className="tabular shrink-0 rounded border border-console-700 bg-console-900/60 px-1.5 py-0.5 text-[10px] text-ink-500">
            {booking.booking_ref}
          </span>
        </div>

        <p className="mt-2.5 flex items-start gap-1.5 text-xs text-ink-300">
          <MapPin className="mt-0.5 size-3 shrink-0 text-signal-400" />
          <span className="min-w-0">
            {booking.pickup}
            <span className="mx-1 text-ink-700">→</span>
            {booking.dropoff}
          </span>
        </p>

        <div className="mt-3 grid grid-cols-3 gap-2">
          <Stat label="Pickup in" value={`${booking.eta_min} min`} tone="signal" />
          <Stat label="Ride time" value={`${booking.ride_duration_min} min`} />
          <Stat
            label="Price (est.)"
            value={`${booking.currency} ${booking.price.toLocaleString("en-LK")}`}
            tone="glow"
          />
        </div>

        {replanFrom && (
          <p className="mt-3 flex items-start gap-1.5 rounded-lg border border-console-700/60 bg-console-900/40 px-2.5 py-2 text-[11px] text-ink-300">
            <Clock className="mt-px size-3 shrink-0 text-signal-400" />
            <span>
              Onward journey planned from{" "}
              <span className="tabular font-semibold text-signal-400">{replanFrom}</span> —{" "}
              {booking.eta_min} min to pickup plus {booking.ride_duration_min} min in the vehicle,
              not from now.
            </span>
          </p>
        )}

        <p className="mt-2 text-[10px] leading-relaxed text-ink-700">
          Price, ETA and availability are generated by a stand-in backend. No vehicle has been
          dispatched and no payment has been taken.
        </p>
      </div>
    </Panel>
  );
}

function Stat({
  label,
  value,
  tone = "default",
}: {
  label: string;
  value: string;
  tone?: "default" | "signal" | "glow";
}) {
  return (
    <div className="rounded-lg border border-console-700/60 bg-console-900/40 px-2 py-1.5">
      <p className="eyebrow">{label}</p>
      <p
        className={cn(
          "tabular mt-0.5 text-sm font-semibold",
          tone === "signal" && "text-signal-400",
          tone === "glow" && "text-glow-400",
          tone === "default" && "text-ink-100",
        )}
      >
        {value}
      </p>
    </div>
  );
}
